### ISSUE TITLE
there a config for this? 

### ISSUE THREAD

**Issue by just-rich** [3nws/beako-dashboard#1]
been looking for an alternative to statcord as they abandoned it and it stopped working over the past week. seems like opensource or self hosted is the only other option.

this isn't pretty but it's simple and has stats that im looking for. but keep getting "can't connect to X server"

![image](https://user-images.githubusercontent.com/87265195/235885473-8036e7f5-bdbd-4f63-8aa6-8d4e608935c0.png)

**Comment by 3nws** [comment]
Maybe you don't have X11 installed? Is this a container? Anyway, I never used statcord so I don't know what configurations you'd have to make to your bot. But for this, you need to setup a socket server in your [`setup_hook`](https://github.com/3nws/beako-bot/blob/main/app/Bot.py#L130) and [send](https://github.com/3nws/beako-bot/blob/main/app/Bot.py#LL94C15-L94C25) whatever info you want. 

I didn't spend much time on this and haven't used it in a while. You might want to look for another alternative.
